package com.example.restaurantreview

import java.io.Serializable

data class Restaurants(
            var restaurant_link:String?=null,
            var restaurant_name:String?=null,
            var original_location:String? =null,
            var country:String? =null,
            var region:String? =null,
            var province:String? =null,
            var city:String? =null,
            var address:String? =null,
            var latitude:Float? =null,
            var longitude:Float? = null,
            var claimed:String? =null,
            var awards:String? =null,
            var popularity_detailed:String? =null,
            var popularity_generic:String? =null,
            var top_tags:String? =null,
            var price_level:String? =null,
            var price_range:String? =null,
            var meals:String? =null,
            var cuisines:String? =null,
            var special_diets:String? =null,
            var features:String? =null,
            var vegetarian_friendly:String? =null,
            var vegan_options:String? =null,
            var gluten_free:String? =null,
            var original_open_hours:String? =null,
            var open_days_per_week:String? =null,
            var open_hours_per_week:String? =null,
            var working_shifts_per_week:String? =null,
            var avg_rating:Float?=null,
            var total_reviews_count:Float?=null,
            var default_language:String? =null,
            var reviews_count_in_default_language: Float?=null,
            var excellent: Float?=null,
            var very_good: Float?=null,
            var average :Float?=null,
            var poor :Float?=null,
            var terrible :Float?=null,
            var food :Float?=null,
            var service :Float?=null,
            var value :Float?=null,
            var atmosphere:String? =null,
            var keywords:String? =null, ):Serializable


